### PR TITLE
Add /getrole (extension): allow RB members to self-assign roles

### LINKED ISSUE #13: Self service roles for Webgroup and Games (reaction/slash command)

### PR DESCRIPTION
**Pull request by koyakonsta**
closes #13

### CODE REVIEW

**Comment by koyakonsta** [comment]
- xoreax.

**Comment by koyakonsta** [comment]
tested locally. WORKS ON MY MACHINE. will pull soon

**Comment by DistroByte** [comment]
Hot take, `gib` is not a good command name. Would `/role` make more sense?

**Comment by koyakonsta** [comment]
> Hot take, `gib` is not a good command name. Would `/role` make more sense?

Probably XD. Changed it now. Would /getrole or /giverole work too?

**Comment by DistroByte** [comment]
Yeah `getrole` would be a better command name I think

**Comment by koyakonsta** [comment]
> Yeah `getrole` would be a better command name I think

cool.

**Review by DistroByte — APPROVED** [review]
LGTM, but let's test it first before merging

**Comment by JedHazaymeh** [comment]
Not sure how Discord permissions will work with the role adding, or how necessary error handling is here. A review deployment should answer these concerns.

**Comment by JedHazaymeh** [comment]
Closed by #23

**Pull request closed without merging**
