### PR TITLE
Add Ruff to pre-commit

### PR DESCRIPTION
**Pull request by Ne-wt**
Adds Ruff (mentioned in issue #31). 
This does not add nox as mentioned in issue 31 as nox is for "for automated testing" as mentioned on the issue so out of this PR's scope
uses pre-commit

### CODE REVIEW

**Comment by Ne-wt** [comment]
I would like to mention that black and ruff have of course been run on this commit(s)

**Comment by JedHazaymeh** [comment]
> I would like to mention that black and ruff have of course been run on this commit(s)

I noticed 😆 I am judging the styling. Are the current rules the default (and/or the recommended standard)?

**Comment by Ne-wt** [comment]
> I noticed 😆 I am judging the styling. Are the current rules the default (and/or the recommended standard)?

yes current linting is by PEP 8 standards and default, no configs added etc

**Review by JedHazaymeh — APPROVED** [review]
LGTM 🚀

**Pull request merged**
